language: lua
os:
- linux
dist: xenial
before_install:
- sudo apt-get install make libxslt tshark
install: true
script:
- cd tests
- make clean
- make test
notifications:
  slack:
    secure: P0MGZdsGLQ8CGQ/Ok2ufXQWxNTBSZzh0FhAgoKlQkCDhFDWo7RXGqaw3cB5HsdiasSEVqFTj0adAllvNyaf9QOI5+TyUUuGKN2Wwdh1rbMwn8ko2N67JdtsyN7uOV/xWM6tgp70uFi4NjRRKwPdgCke+MIOfAmmAIMkCpKQtzu5Kv9jqT+6+Y2uGSKz5v/D5o6BSNhksLu+iuzjyR82B/C1VS9MiSjP5hlLukXx4BYe233yw2CHLUqGwEszDo+R6AT7YkA8PJkBSfX1I0xjJHKSd8sUQWE7APUGUNdWiqRKyOJSEgpCaVFo76P0/yeIcg6XoV38WCw5m5In8sQHmSCuE5V0VNm6BenqUOKs/BnZLPXlbrECSQbOUXnuAT6dfXbo/0evROxGKq9Wdk86jPrckM8UdemPZLhZxY7y5B1yjZbdNLSKF5ZdWtviB7grct+XTpqLOcP5nwjft9raFqbEPdqCxta2eajwQja67wolmDQSura9Hin5+xeE0ZCkC+/E/tPbABnSyoiDfZ5L0AFyLBp/FoFvuCknZ0eeVzSeNf2RaUcCAwwQ2rwYTE/wYUr8NDnqlt1rehrLPudi4gsnwpJy5GBsGsdxzjOgjxGaPuA8o1RcCxHPfLPSMIxkDVQNIO1T1+5e5tnrBk7y6GskPIcqNusAnR5KV/dlDHqk=
